# Makefile for Creatures Sprites Gimp-Plugin
# for Mingw32/Cygwin
#

include makeinc.g95

all:
	$(MAKE) -C $(SRCDIR) -f Makefile.g95 
	msgfmt --verbose -o $(LOCALSDIR)/$(PLUGIN_NAME).mo $(LOCALSDIR)/de.po

clean:
	$(MAKE) -C $(SRCDIR) -f Makefile.g95 clean
	$(RM) $(LOCALESDIR)/*.mo

install: $(SRCDIR)/*.c
	$(MAKE) -C $(SRCDIR) -f Makefile.g95 install
	cp $(LOCALSDIR)/$(PLUGIN_NAME).mo $(LOCALEDIR)/de/LC_MESSAGES

.PHONY: clean
